### PR TITLE
194 fingerprint dialog orientation changed

### LINKED ISSUE #194: [Crash] App crashes on orientation changed, when fingerprint dialog is displayed
Go to Lock screen or Settings screen. Tap on Unlock button or toggle button for enabling fingerprint. After the fingerprint dialog is displayed, change the orientation of the device => app crashes

### PR DESCRIPTION
**Pull request by ioana-farcas**
Fixes #194 

## Testing and Review Notes
Please verify behaviour at orientation change for Lock screen and Settings screen.

## To Do

- add “WIP” to the PR title if pushing up but not complete nor ready for review
- [x] double check the original issue to confirm it is fully satisfied
- [ ] add testing notes and screenshots in PR description to help guide reviewers
- [x] add unit tests
  - optional: consider adding instrumentation (integration/UI) tests
- consider running this branch in a debug simulator and check for memory leak notifications or any warnings
- [x] request the "UX" team perform a design review (if/when applicable)
- [x] make sure CI builds are passing (e.g.: fix lint and other errors)
- [ ] ~~check on the [accessibility](https://mozilla-lockbox.github.io/lockbox-android/accessibility/) of any added UI~~

### CODE REVIEW

File: app/src/main/java/mozilla/lockbox/adapter/SettingListAdapter.kt [hunk 1]
```diff
@@ -81,24 +83,20 @@ class SettingListAdapter : RecyclerView.Adapter<SettingViewHolder>() {
...
+            else -> throw IllegalStateException("Please use a valid defined setting type.")
         }
     }
 
     fun setItems(settingConfig: List<SettingCellConfiguration>) {
         settingListConfig = settingConfig
         notifyDataSetChanged()
     }
+
+    override fun onDetachedFromRecyclerView(recyclerView: RecyclerView) {
```
Comment (sashei) [inline app/src/main/java/mozilla/lockbox/adapter/SettingListAdapter.kt]: ooo

File: app/src/main/java/mozilla/lockbox/adapter/SettingListAdapter.kt [hunk 2]
```diff
@@ -81,24 +83,20 @@ class SettingListAdapter : RecyclerView.Adapter<SettingViewHolder>() {
...
-                return SETTING_TOGGLE_TYPE
-            }
-            is AppVersionSettingConfiguration -> {
-                return SETTING_APP_VERSION_TYPE
-            }
-            else -> {
-                throw IllegalStateException("Please use a valid defined setting type.")
-            }
+        return when (configurationType) {
+            is TextSettingConfiguration -> SETTING_TEXT_TYPE
```
Comment (sashei) [inline app/src/main/java/mozilla/lockbox/adapter/SettingListAdapter.kt]: 👍

File: app/src/main/java/mozilla/lockbox/adapter/SettingListAdapter.kt [hunk 3]
```diff
@@ -51,7 +53,7 @@ class SettingListAdapter : RecyclerView.Adapter<SettingViewHolder>() {
     }
 
     override fun onBindViewHolder(holder: SettingViewHolder, position: Int) {
-        holder.compositeDisposable.clear()
+        holder.disposable?.let { compositeDisposable.remove(holder.disposable!!) }
```
Comment (jhugman) [inline app/src/main/java/mozilla/lockbox/adapter/SettingListAdapter.kt]: This looks needlessly complicated. Also avoid `!!`.

Would work: 
```kt
 holder.disposable?.let { compositeDisposable.remove(it) }
```

File: app/src/main/java/mozilla/lockbox/adapter/SettingListAdapter.kt (hunk 1 above)
Comment (jhugman) [reply app/src/main/java/mozilla/lockbox/adapter/SettingListAdapter.kt]: 👍

File: app/src/main/java/mozilla/lockbox/presenter/SettingPresenter.kt [hunk 4]
```diff
@@ -43,15 +44,18 @@ class SettingPresenter(
 
     private val versionNumber = BuildConfig.VERSION_NAME
 
-    private val autoLockObserver: Consumer<Boolean>
+    val autoLockObserver: Consumer<Boolean>
```
Comment (jhugman) [inline app/src/main/java/mozilla/lockbox/presenter/SettingPresenter.kt]: I'm confused why this is a consumer, and everything else is an `Observer`, or a closure used to subscribe.

A tiny comment here would be helpful. 

```
// we use a Consumer here because…
```

File: app/src/main/java/mozilla/lockbox/adapter/SettingListAdapter.kt (hunk 3 above)
Comment (ioana-farcas) [reply app/src/main/java/mozilla/lockbox/adapter/SettingListAdapter.kt]: 👍

File: app/src/main/java/mozilla/lockbox/presenter/SettingPresenter.kt (hunk 4 above)
Comment (ioana-farcas) [reply app/src/main/java/mozilla/lockbox/presenter/SettingPresenter.kt]: For each toggle button a Consumer is used as a callback in the subscribe method. This is because when switching the toggle button, there is no need for the onError or other events except onNext . As far as I understand, when only one event is needed, there is no reason to use an Observer and implement all the events (onNext, onError, onComplete..). Instead a Consumer can be used. I will add a comment if you think it's necessary.

Comment (sashei) [reply app/src/main/java/mozilla/lockbox/presenter/SettingPresenter.kt]: IMO the comment might not be necessary; we only use `Consumer`s in the `SettingPresenter`. It also has the advantage of tying the lifecycle to the view.

Comment (jhugman) [reply app/src/main/java/mozilla/lockbox/presenter/SettingPresenter.kt]: :+1:

**Comment by ioana-farcas** [comment]
@jhugman I changed the naming to **UnlockWithFingerprintPendingAuth**. Please let me know if this is ok with you
