### PR TITLE
appropriate behavior when backgrounding autofill + locking

### LINKED ISSUE #489: Backgrounding Autofill for some period > autolock time will launch the fingerprint dialog again
Steps to reproduce:
- Launch into the Search view in autofill (either unlocking or from Search Your Entries row)
- Use the home button or simply let the device go to sleep for > 5minutes (or whatever the autolock time is)

**expected:** the search dialog goes away, only the fingerprint dialog remains
**actual:** a second fingerprint dialog is launched over the search dialog. unlocking brings you to a second search dialog.

### PR DESCRIPTION
**Pull request by sashei**
Fixes #489

## Testing and Review Notes

The best way that I found to test this was to try to autofill a site for which we have no credentials. I would subsequently enter something into the search box so that it's expanded with some results, and then put the device to sleep for the autolock time. Ideally, upon unlocking the device, the search dialog goes away and the fingerprint or PIN screen is shown.

## To Do

- [x] double check the original issue to confirm it is fully satisfied
- [x] add testing notes and screenshots in PR description to help guide reviewers
- [x] add unit tests
- [x] make sure CI builds are passing (e.g.: fix lint and other errors)

### CODE REVIEW

File: app/src/main/java/mozilla/lockbox/presenter/AutofillRoutePresenter.kt [hunk 1]
```diff
@@ -146,6 +156,14 @@ class AutofillRoutePresenter(
         }
     }
 
+    private fun <T : DialogFragment> dismissDialogIfPresent(clazz: Class<T>) {
+        val fragmentManager = activity.supportFragmentManager
+        val presentedDialog = fragmentManager.findFragmentByTag(clazz.name)
+        log.info("presented dialog: $presentedDialog")
```
Comment (jhugman) [inline app/src/main/java/mozilla/lockbox/presenter/AutofillRoutePresenter.kt]: In general, I don't like that the route needs to have fore-knowledge of the dialog that we're moving from.

Additionally, I'm not entirely sure if this is only working accidentally. I think I'd prefer to see a 

```kotlin
<T : Fragment> fun FragmentManager.findChildFragmentByClass(clazz: Class<T>)
```

which looks at `fragment.childFragmentManager` of each fragment (currently, `showDialogFragment` uses the `NavHostFragment` as the `currentFragment`).

File: app/src/main/java/mozilla/lockbox/presenter/AutofillRoutePresenter.kt [hunk 2]
```diff
@@ -111,12 +115,18 @@ class AutofillRoutePresenter(
...
             if (clearBackStack) {
                 while (navController.popBackStack()) {
                     // NOP
                 }
             }
+
+            action?.let {
+                navController.navigate(it.destinationId, args, it.navOptions)
+                return
+            }
```
Comment (jhugman) [inline app/src/main/java/mozilla/lockbox/presenter/AutofillRoutePresenter.kt]: The sooner we rationalize `AutofillRoutePresenter` and `RoutePresenter` the better.

Comment (sashei) [reply app/src/main/java/mozilla/lockbox/presenter/AutofillRoutePresenter.kt]: https://github.com/mozilla-lockbox/lockbox-android/issues/508

File: app/src/main/java/mozilla/lockbox/presenter/AutofillRoutePresenter.kt [hunk 3]
```diff
@@ -128,10 +138,10 @@ class AutofillRoutePresenter(
     }
 
     private fun findTransitionId(@IdRes from: Int, @IdRes to: Int): Int? {
-        return when (Pair(from, to)) {
-            Pair(R.id.fragment_locked, R.id.fragment_filter) -> R.id.action_locked_to_filter
-            Pair(R.id.fragment_null, R.id.fragment_filter) -> R.id.action_to_filter
-            Pair(R.id.fragment_null, R.id.fragment_locked) -> R.id.action_to_locked
+        return when (from to to) {
```
Comment (eliserichards) [inline app/src/main/java/mozilla/lockbox/presenter/AutofillRoutePresenter.kt]: I would rename `to`. Suggestions: `start to end`, `begin to end`, `from to dest`/`destination`...

File: app/src/main/java/mozilla/lockbox/presenter/AutofillRoutePresenter.kt (hunk 1 above)
Comment (sashei) [reply app/src/main/java/mozilla/lockbox/presenter/AutofillRoutePresenter.kt]: I don't know if I'd call this "accidental" but I would call it "hacky" ;)

it relies on us setting the tag for the dialog fragments to their respective class names as obtained by `clazz.name`.... I'm open to other solutions tho.

File: app/src/main/java/mozilla/lockbox/presenter/AutofillRoutePresenter.kt [hunk 4]
```diff
@@ -101,51 +121,61 @@ class AutofillRoutePresenter(
...
+            dialogFragment.show(navHostFragmentManager, dialogFragment.javaClass.name)
             dialogFragment.setupDialog(destination.dialogTitle, destination.dialogSubtitle)
         } catch (e: IllegalStateException) {
             log.error("Could not show dialog", e)
         }
     }
 
+    private fun dismissDialogIfPresent() {
+        (currentFragment as? DialogFragment)?.dismiss()
+    }
```
Comment (jhugman) [inline app/src/main/java/mozilla/lockbox/presenter/AutofillRoutePresenter.kt]: ✅ ✅ ✅

File: app/src/test/java/mozilla/lockbox/presenter/AutofillRoutePresenterTest.kt [hunk 5]
```diff
@@ -86,6 +88,15 @@ class AutofillRoutePresenterTest {
...
     val fragmentManager: FragmentManager = mock(FragmentManager::class.java)
 
+    @Mock
+    val childFragmentManager: FragmentManager = mock(FragmentManager::class.java)
+
+    @Mock
+    val currentFragment: DialogFragment = mock(DialogFragment::class.java)
+
+    @Mock
+    val navHost: Fragment = mock(Fragment::class.java)
```
Comment (jhugman) [inline app/src/test/java/mozilla/lockbox/presenter/AutofillRoutePresenterTest.kt]: Ah great, this is good to see tested.

File: app/src/main/res/navigation/graph_main.xml [hunk 6]
```diff
@@ -9,9 +9,9 @@
             xmlns:app="http://schemas.android.com/apk/res-auto"
             xmlns:tools="http://schemas.android.com/tools"
             android:id="@+id/graph_main"
-            app:startDestination="@id/fragment_null">
+            app:startDestination="@id/fragment_filter_backdrop">
     <fragment
-            android:id="@+id/fragment_null"
+            android:id="@+id/fragment_filter_backdrop"
```
Comment (jhugman) [inline app/src/main/res/navigation/graph_main.xml]: I think that this is a little over zealous refactoring by Android Studio.

File: app/src/main/java/mozilla/lockbox/presenter/RoutePresenter.kt [hunk 7]
```diff
@@ -230,9 +230,9 @@ class RoutePresenter(
         // If a RouteAction is called from a place the graph doesn't know about then
         // the app will log.error.
         return when (from to to) {
-            R.id.fragment_null to R.id.fragment_item_list -> R.id.action_init_to_unlocked
-            R.id.fragment_null to R.id.fragment_locked -> R.id.action_init_to_locked
-            R.id.fragment_null to R.id.fragment_welcome -> R.id.action_init_to_unprepared
+            R.id.fragment_filter_backdrop to R.id.fragment_item_list -> R.id.action_init_to_unlocked
+            R.id.fragment_filter_backdrop to R.id.fragment_locked -> R.id.action_init_to_locked
+            R.id.fragment_filter_backdrop to R.id.fragment_welcome -> R.id.action_init_to_unprepared
```
Comment (jhugman) [inline app/src/main/java/mozilla/lockbox/presenter/RoutePresenter.kt]: I think that this is a little over zealous refactoring by Android Studio.

File: app/src/main/java/mozilla/lockbox/presenter/AutofillRoutePresenter.kt [hunk 8]
```diff
@@ -101,51 +121,61 @@ class AutofillRoutePresenter(
...
 
-    private fun findTransitionId(@IdRes from: Int, @IdRes to: Int): Int? {
-        return when (Pair(from, to)) {
-            Pair(R.id.fragment_locked, R.id.fragment_filter) -> R.id.action_locked_to_filter
-            Pair(R.id.fragment_null, R.id.fragment_filter) -> R.id.action_to_filter
-            Pair(R.id.fragment_null, R.id.fragment_locked) -> R.id.action_to_locked
+    private fun findTransitionId(@IdRes from: Int, @IdRes destination: Int): Int? {
+        return when (from to destination) {
+            R.id.fragment_locked to R.id.fragment_filter_backdrop -> R.id.action_to_filter
+            R.id.fragment_filter_backdrop to R.id.fragment_locked -> R.id.action_to_locked
```
Comment (jhugman) [inline app/src/main/java/mozilla/lockbox/presenter/AutofillRoutePresenter.kt]: Nit: use `src` and `dest` here. `from` and `destination` is mixing your metaphors, like comparing `chalk` and `oranges`.

File: app/src/main/java/mozilla/lockbox/presenter/AutofillRoutePresenter.kt [hunk 9]
```diff
@@ -82,10 +96,16 @@ class AutofillRoutePresenter(
...
-            is RouteAction.LockScreen -> navigateToFragment(R.id.fragment_locked)
-            is RouteAction.ItemList -> showDialogFragment(AutofillFilterFragment(),
-                RouteAction.DialogFragment.AutofillSearchDialog
-            )
+            is RouteAction.LockScreen -> {
+                dismissDialogIfPresent()
+                navigateToFragment(R.id.fragment_locked)
+            }
+            is RouteAction.ItemList -> {
+                dismissDialogIfPresent()
```
Comment (jhugman) [inline app/src/main/java/mozilla/lockbox/presenter/AutofillRoutePresenter.kt]: I'm still not altogether happy with `dismissDialogIfPresent`. It feels like the dialog is not cleaning up after its own mess.

File: app/src/main/res/navigation/graph_autofill.xml [hunk 10]
```diff
@@ -9,17 +9,12 @@
             xmlns:app="http://schemas.android.com/apk/res-auto"
             xmlns:tools="http://schemas.android.com/tools"
             android:id="@+id/graph_autofill"
-            app:startDestination="@id/fragment_null">
+            app:startDestination="@id/fragment_filter_backdrop">
```
Comment (jhugman) [inline app/src/main/res/navigation/graph_autofill.xml]: This looks like it should cause problems when the app is locked. 

I think I'd prefer to keep using blank and then move on to the `AutofillFilterBackdropFragment`. This makes it congruent with the `graph_main.xml`.

File: app/src/main/java/mozilla/lockbox/presenter/AutofillFilterBackdropPresenter.kt [hunk 11]
```diff
@@ -0,0 +1,28 @@
...
+
+interface AutofillFilterBackdropView
+
+class AutofillFilterBackdropPresenter(
+    val view: AutofillFilterBackdropView,
+    private val dispatcher: Dispatcher = Dispatcher.shared
+) : Presenter() {
+    override fun onViewReady() {
+        Observable.just(RouteAction.DialogFragment.AutofillSearchDialog)
+            .delay(1, TimeUnit.SECONDS)
```
Comment (eliserichards) [inline app/src/main/java/mozilla/lockbox/presenter/AutofillFilterBackdropPresenter.kt]: What is the purpose of this `delay`?

File: app/src/main/java/mozilla/lockbox/presenter/AutofillRoutePresenter.kt (hunk 9 above)
Comment (eliserichards) [reply app/src/main/java/mozilla/lockbox/presenter/AutofillRoutePresenter.kt]: Can this be handled in the navigation instead of here? It doesn't seem to make sense.

File: app/src/main/java/mozilla/lockbox/presenter/AutofillRoutePresenter.kt (hunk 4 above)
Comment (eliserichards) [reply app/src/main/java/mozilla/lockbox/presenter/AutofillRoutePresenter.kt]: Why isn't the `dialog` set up to be dismissed on its own? Should we be doing this same thing for the `RoutePresenter`'s `showDialogFragment`? https://github.com/mozilla-lockbox/lockbox-android/blob/ac8add36bd4c79ad0b6db11881b5da928a2bbaa2/app/src/main/java/mozilla/lockbox/presenter/RoutePresenter.kt#L166

File: app/src/main/java/mozilla/lockbox/view/AutofillFilterFragment.kt [hunk 12]
```diff
@@ -84,9 +85,12 @@ class AutofillFilterFragment : DialogFragment(), AutofillFilterView {
         adapter.displayNoEntries(enabled)
     }
 
-    override fun onDestroyView() {
+    override fun onCancel(dialog: DialogInterface) {
         (onDismiss as PublishSubject).onNext(Unit)
+        super.onCancel(dialog)
```
Comment (eliserichards) [inline app/src/main/java/mozilla/lockbox/view/AutofillFilterFragment.kt]: Would ``` (currentFragment as? DialogFragment)?.dismiss()``` relavent here?

File: app/src/main/java/mozilla/lockbox/presenter/AutofillFilterBackdropPresenter.kt (hunk 11 above)
Comment (sashei) [reply app/src/main/java/mozilla/lockbox/presenter/AutofillFilterBackdropPresenter.kt]: It ensures that the correct fragment is presented before the `DialogFragment` gets presented / attached

File: app/src/main/java/mozilla/lockbox/presenter/AutofillRoutePresenter.kt (hunk 4 above)
Comment (sashei) [reply app/src/main/java/mozilla/lockbox/presenter/AutofillRoutePresenter.kt]: We don't have the same situation in the normal app; we rarely have to dismiss a dialog _without_ anything being tapped on it.
