### PR TITLE
Fixup no-username bugs (crash and string change)

### LINKED ISSUE #488: No username entry crashes with "null pointer item detail fragment"
Steps to reproduce: 

1. login
2. navigate to the item list screen.
3. Tap on a login with an empty username

Expected: 
An item detail screen including the username field as "(no username)". 

Observed: 
The app crashes with a `NullPointerException`.

### PR DESCRIPTION
**Pull request by jhugman**
Fixes #488.

This PR fixes a crash caused by `kotlinx.android` auto generated code being incorrectly generated and incorrectly used. This PR does not address the generated code, which allowed: 

```kotlin
inputUsername.btnUsernameCopy
```

to be used, which resolves to `null`.

It also addresses an issue in autofill which caused strings containing "null" in display strings for autofill.

### CODE REVIEW

File: app/src/main/java/mozilla/lockbox/autofill/FillResponseBuilder.kt [hunk 1]
```diff
@@ -97,25 +97,26 @@ open class FillResponseBuilder(
...
                 .apply {
-                    setTextViewText(R.id.autofillValue, credential.username)
+                    setTextViewText(R.id.autofillValue, username)
                     setTextViewText(R.id.hostname, title)
                 }
 
             datasetBuilder.setValue(
                 it,
-                AutofillValue.forText(credential.username),
+                AutofillValue.forText(credential.username ?: ""),
```
Comment (eliserichards) [inline app/src/main/java/mozilla/lockbox/autofill/FillResponseBuilder.kt]: what happens when the `credential.username` is null?

Comment (jhugman) [reply app/src/main/java/mozilla/lockbox/autofill/FillResponseBuilder.kt]: When the `credential.username` is `null`, the empty string is used instead.

This means that the input field would be filled with the empty string rather than "null". (i.e. `null.toString()`)

Comment (jhugman) [reply app/src/main/java/mozilla/lockbox/autofill/FillResponseBuilder.kt]: @eliserichards I've added steps to reproduce in the original issue #488
