### PR TITLE
Capture OAuth Redirect before it can be Displayed

### LINKED ISSUE #296: Lockbox Android :: FxA Redirect Landing page is displayed after login
## Steps to reproduce

1. Open Lockbox
2. Tap on "Get Started"
3. Login with valid credentials
### Expected behavior
The login is successfully made and no errors are displayed.
### Actual behavior
The Lockbox Android :: FxA Redirect Landing page is displayed after login.
### Device and build information
* Firefox Lockbox version: 1.0([build #1785](https://app.bitrise.io/build/8d9b6261fed6330c))
* Google Pixel 3 XL (Android 9)
* Samsung Galaxy Note 9 (Android 8.1.0)
* Sony Xperia (Android 6)
### Notes
[Video](https://goo.gl/Fxdr8J)
[Logcat](https://github.com/mozilla-lockbox/lockbox-android/files/2694422/Logcat.txt)

### PR DESCRIPTION
**Pull request by linuxwolf**
This change properly captures the OAuth redirect URI and instructs the webView that the application will handle it rather than letting the default rendering occur.

Fixes #296

_(**Required**: this reference (one or many) will be closed upon merge. Ideally it has the acceptance criteria and designs for features or fixes related to the work in this Pull Request.)_

## Testing and Review Notes

**Prerequisites**

* not signed into FxA in Lockbox

**Steps**

* Open Lockbox
* Click "Get Started"
* Complete FXA sign-in/sign-up flow

_(**Required**: steps to take to confirm this works as expected or other guidance for code, UX, and any other reviewers)_

## Screenshots or Videos

no-show-redirect

## To Do

- ~add “WIP” to the PR title if pushing up but not complete nor ready for review~
- [x] double check the original issue to confirm it is fully satisfied
- [x] add testing notes and screenshots in PR description to help guide reviewers
- [x] add unit tests
  - optional: consider adding instrumentation (integration/UI) tests
- consider running this branch in a debug simulator and check for memory leak notifications or any warnings
- [ ] request the "UX" team perform a design review (if/when applicable)
- [x] make sure CI builds are passing (e.g.: fix lint and other errors)
- ~check on the [accessibility](https://mozilla-lockbox.github.io/lockbox-android/accessibility/) of any added UI~

### CODE REVIEW

File: app/src/test/java/mozilla/lockbox/presenter/FxALoginPresenterTest.kt [hunk 1]
```diff
@@ -79,7 +89,7 @@ class FxALoginPresenterTest {
 
     @Test
     fun `onViewReady, when the webview redirects to a URL starting with the expected redirect`() {
-        val url = Constant.FxA.redirectUri + "/moz_fake"
+        val url = Constant.FxA.redirectUri + "?moz_fake"
```
Comment (linuxwolf) [inline app/src/test/java/mozilla/lockbox/presenter/FxALoginPresenterTest.kt]: this is (slightly) closer to what would be seen.

**Comment by linuxwolf** [comment]
@mozilla-lockbox/ux I don't think this needs your review, but feel free to take a look!

File: app/src/main/java/mozilla/lockbox/view/FxALoginFragment.kt [hunk 2]
```diff
@@ -53,10 +53,13 @@ class FxALoginFragment : BackableFragment(), FxALoginView {
 
     override fun loadURL(url: String) {
         webView.webViewClient = object : WebViewClient() {
-            override fun onPageStarted(view: WebView?, url: String?, favicon: Bitmap?) {
-                webViewObserver?.accept(url)
-
-                super.onPageStarted(view, url, favicon)
+            override fun shouldOverrideUrlLoading(view: WebView?, request: WebResourceRequest?): Boolean {
+                val url = request?.url.toString() ?: null
+                if ((presenter as FxALoginPresenter).isRedirectUri(url)) {
```
Comment (sashei) [inline app/src/main/java/mozilla/lockbox/view/FxALoginFragment.kt]: Architecture-wise, this is a little too much knowledge about the `Presenter` from the `View` perspective. Rather than doing this force-cast and calling a function on the presenter, I would prefer to see the `FxAView` interface amended to look something like this:
```kotlin
interface FxALoginView {
    var webViewRedirect: ((url: URL?) -> Boolean)?
    val skipFxAClicks: Observable<Unit>?
    fun loadURL(url: String)
}
```

In the `onViewReady` of the `Presenter`, you can assign the anonymous function to carry out the same actions as the `webViewObserver` did, but additionally return the `isRedirectURI` value. The `shouldOverrideURLLoading` function would then be able to simply consist of 
```kotlin
return webViewRedirect(request?.url)
```
