### PR TITLE
nullsafe operations on FingerprintManager 

### LINKED ISSUE #207: [Crash] TypeCastException in FingerprintManager
Reported in Play Store pre-launch checklist tests on 
Xperia XZ1 Compact with Android 8.0:

>Issue: java.lang.RuntimeException: Unable to create application mozilla.lockbox.LockboxApplication: kotlin.TypeCastException: null cannot be cast to non-null type android.hardware.fingerprint.FingerprintManager

```
FATAL EXCEPTION: main
Process: mozilla.lockbox, PID: 13148
java.lang.RuntimeException: Unable to create application mozilla.lockbox.LockboxApplication: kotlin.TypeCastException: null cannot be cast to non-null type android.hardware.fingerprint.FingerprintManager
	at android.app.ActivityThread.handleBindApplication(ActivityThread.java:5825)
	at android.app.ActivityThread.-wrap1(Unknown Source:0)
	at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1666)
	at android.os.Handler.dispatchMessage(Handler.java:105)
	at android.os.Looper.loop(Looper.java:251)
	at android.app.ActivityThread.main(ActivityThread.java:6572)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.Zygote$MethodAndArgsCaller.run(Zygote.java:240)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:767)
Caused by: kotlin.TypeCastException: null cannot be cast to non-null type android.hardware.fingerprint.FingerprintManager
	at mozilla.lockbox.LockboxApplication.onCreate(LockboxApplication.kt:59)
	at android.app.Instrumentation.callApplicationOnCreate(Instrumentation.java:1119)
	at android.app.ActivityThread.handleBindApplication(ActivityThread.java:5822)
	... 8 more
```

_Originally posted by @devinreams in https://github.com/mozilla-lockbox/lockbox-android/issues/194#issuecomment-437963871_

### PR DESCRIPTION
**Pull request by jmedveckyh**
Fixes #207 

## Testing and Review Notes

Just build it and install on older device, such as Nexus 4 where it won't event start and now it works properly.

## To Do

- [x] double check the original issue to confirm it is fully satisfied
- [x] add testing notes and screenshots in PR description to help guide reviewers
- [x] modify unit tests
- [x] make sure CI builds are passing (e.g.: fix lint and other errors)

### CODE REVIEW

File: app/src/main/java/mozilla/lockbox/store/FingerprintStore.kt [hunk 1]
```diff
@@ -84,7 +84,7 @@ open class FingerprintStore(
         get() = isFingerprintAuthAvailable || isKeyguardDeviceSecure
 
     open val isFingerprintAuthAvailable: Boolean
-        get() = fingerprintManager.isHardwareDetected && fingerprintManager.hasEnrolledFingerprints()
+        get() = (fingerprintManager?.isHardwareDetected ?: false) && (fingerprintManager?.hasEnrolledFingerprints() ?: false)
```
Comment (beatbrot) [inline app/src/main/java/mozilla/lockbox/store/FingerprintStore.kt]:
```suggestion
        get() = fingerprintManager != null && fingerprintManager!!.isHardwareDetected && fingerprintManager!!.hasEnrolledFingerprints()
```

How about checking for null first and then asserting that the fingerprintManager is not null? Would clean up code imo

Comment (sashei) [reply app/src/main/java/mozilla/lockbox/store/FingerprintStore.kt]: Thanks for the recommendation @beatbrot !! We avoid force-unwraps `!!` unless _absolutely_ necessary, as this code is executed sequentially and the `fingerprintManager` may become null (it's a `var`) after the null-check has happened.
