### PR TITLE
Formatting xml for autofill popup

### LINKED ISSUE #436: Visual Tidy DataSet presentation XML for autofill
Followup from #413 

The priority for landing #413 is such that the implementation of the popup is not consistent with the designs.

### Visual Design

**InVision**
Initial (1 entry): https://mozilla.invisionapp.com/share/3SN35UHWJDX#/317564412_Autofill_-_App_-_Initial
Initial (multiple entries): https://mozilla.invisionapp.com/share/3SN35UHWJDX#/317564409_Autofill_-_App_-_Initial_-multiple_Entries-
Initial (no matching entries): https://mozilla.invisionapp.com/share/3SN35UHWJDX#/317568427_Autofill_-_App_-_No_Matches
Unlock (fingerprint): https://mozilla.invisionapp.com/share/3SN35UHWJDX#/317564407_Autofill_-_App_-_Unlock_-_Fingerprint
Unlock (Device PIN/Pattern): https://mozilla.invisionapp.com/share/3SN35UHWJDX#/310610372_Lock_Screen_-_Device_PIN
Filled: https://mozilla.invisionapp.com/share/3SN35UHWJDX#/317564408_Autofill_-_App_-_Filled

**Zeplin**
Initial (1 entry): https://zpl.io/2pBe6lE
Initial (multiple entries): https://zpl.io/aNo8g9v
Initial (no matching entries): https://zpl.io/a7ENAJR
Unlock (fingerprint): https://zpl.io/bLD0zx7
Unlock (Device PIN/Pattern): https://zpl.io/bAqXRm6

### LINKED ISSUE #469: Look into flakey DataStoreTest cases
Both the `testResetSupport` and `receiving background actions when locked` tests have been failing sporadically, both locally and in CI. This creates wasted developer time and CI resources in retrying over and over again to get green builds when nothing related to the `DataStore` has changed.

### LINKED ISSUE #476: Add search footer dataset to each fill response.
PR #471 establishes a search/filtered list to be shown when the datastore does not have any matching logins.

This should also be available anytime the user gets triggers the autofill. 

This should be done by adding an [authenticated dataset][1].

Work in this bug: 

1. add an authenticated dataset with a search presentation, in the `FillResponseBuilder`.
2. style the presentation
3. ensure that tapping on the search presentation takes you to the search/filter list.

We should like to use the same presentation for the "fallback" fill response. 

Designs: [Invision][2]

[1]: https://developer.android.com/reference/android/service/autofill/Dataset.Builder.html#setAuthentication(android.content.IntentSender)
[2]: https://mozilla.invisionapp.com/share/3SN35UHWJDX#/screens/317564409_Autofill_-_App_-_Initial_-multiple_Entries-

### PR DESCRIPTION
**Pull request by eliserichards**
Fixes #436
Fixes #476 
Fixes #469 

## Testing and Review Notes
[Based on my testing...]
Autofill not working in:
- Firefox
- Chrome

Autofill **is working** in:
- Focus (websites: Github, Twitter)

## Screenshots or Videos

screenshot feb 27 2019 4_20_07 pm

## To Do

- [x] add “WIP” to the PR title if pushing up but not complete nor ready for review
- [ ] double check the original issue to confirm it is fully satisfied
- [ ] add testing notes and screenshots in PR description to help guide reviewers
- [ ] request the "UX" team perform a design review (if/when applicable)
- [ ] make sure CI builds are passing (e.g.: fix lint and other errors)
- [ ] check on the [accessibility](https://mozilla-lockbox.github.io/lockbox-android/accessibility/) of any added UI

### CODE REVIEW

File: app/src/main/java/mozilla/lockbox/autofill/FillResponseBuilder.kt [hunk 1]
```diff
@@ -26,8 +26,8 @@ class FillResponseBuilder(
         val responseBuilder = FillResponse.Builder()
 
         val authPresentation = RemoteViews(context.packageName, R.layout.autofill_item).apply {
-            val callToAction = context.resources.getString(R.string.autofill_authenticate_cta)
-            setTextViewText(R.id.presentationText, callToAction)
+            val searchFirefoxLockbox = context.resources.getString(R.string.autofill_authenticate_cta)
+            setTextViewText(R.id.searchLockboxText, searchFirefoxLockbox)
```
Comment (jhugman) [inline app/src/main/java/mozilla/lockbox/autofill/FillResponseBuilder.kt]: This `authPresentation` has a variable called `searchFirefoxLockbox`. I think I'd stick with the identifier names that are already there.

File: app/src/main/java/mozilla/lockbox/autofill/FillResponseBuilder.kt [hunk 2]
```diff
@@ -84,9 +84,13 @@ class FillResponseBuilder(
...
         val passwordPresentation = RemoteViews(context.packageName, mozilla.lockbox.R.layout.autofill_item)
-        usernamePresentation.setTextViewText(mozilla.lockbox.R.id.presentationText, credential.username)
+        // sets the autofill_item text to be a username if present
+        usernamePresentation.setTextViewText(
+            mozilla.lockbox.R.id.searchLockboxText,
+            credential.username)
+        // sets the autofill_item text to be a password if present
         passwordPresentation.setTextViewText(
-            mozilla.lockbox.R.id.presentationText,
+            mozilla.lockbox.R.id.searchLockboxText,
```
Comment (jhugman) [inline app/src/main/java/mozilla/lockbox/autofill/FillResponseBuilder.kt]: We should probably `import mozilla.lockbox.R` rather than using the fully qualified name.

I realise this isn't your error, but you're in a great position to fix it.

File: app/src/main/java/mozilla/lockbox/autofill/FillResponseBuilder.kt [hunk 3]
```diff
@@ -100,6 +104,7 @@ class FillResponseBuilder(
                 AutofillValue.forText(credential.password), passwordPresentation)
         }
 
+        // is this building a concatinated length of autofill_items?
```
Comment (jhugman) [inline app/src/main/java/mozilla/lockbox/autofill/FillResponseBuilder.kt]: `RemoteViews` representation == a username, or a password.
`Dataset` == one username/password combination
`FillResponse` == a collection of datasets.

File: app/src/main/res/values/styles.xml [hunk 4]
```diff
@@ -119,4 +119,10 @@
     <style name="NoConnectivityWarning">
         <item name="android:background">@color/gray_73_percent</item>
     </style>
+    <resources>
+        <style name="AutofillHighlightAppearance" parent="android:autofillHighlight">
+            <item name="android:autofilledHighlight" tools:targetApi="o">@drawable/autofill_item</item>
+        </style>
+    </resources>
```
Comment (jhugman) [inline app/src/main/res/values/styles.xml]: Oh, does this work?

If not, I'd suggest making a `values-26/styles.xml` file, and putting it in there.

**Comment by eliserichards** [comment]
@jhugman This commit was really out of date because I was sick yesterday. Just FYI on your driveby :)

File: app/src/main/res/layout-v26/autofill_cta_presentation.xml [hunk 5]
```diff
@@ -0,0 +1,35 @@
...
+        android:paddingStart="16dp"
+        android:paddingEnd="16dp"
+        android:paddingTop="16dp"
+        android:paddingBottom="17dp"
+        android:gravity="start|center_vertical"
+        android:textSize="16sp"
+        android:fontFamily="sans-serif"
+        android:textStyle="normal"
+        android:lineSpacingExtra="6.5sp"
+        android:textColor="@color/text_grey"
```
[the remark this answers is not in the document]
Comment (jhugman) [reply app/src/main/res/layout-v26/autofill_cta_presentation.xml]: Currently from [`colors.xml`][1]:

```xml
<color name="text_grey">#0c0c0d</color>
```

[1]: https://github.com/mozilla-lockbox/lockbox-android/blob/da69a5ce1e7bd9f9787355766652c92a52d6d633/app/src/main/res/values/colors.xml#L16

[the remark this answers is not in the document]
Comment (linuxwolf) [reply app/src/main/res/layout-v26/autofill_cta_presentation.xml]: apologies; for some reason, I transposed values.

File: app/src/test/java/mozilla/lockbox/mocks/MockLoginsStorage.kt [hunk 6]
```diff
@@ -71,10 +71,11 @@ open class MockLoginsStorage : LoginsStorage {
...
 class MockDataStoreSupport : DataStoreSupport {
     val storage = Mockito.spy<MockLoginsStorage>(MockLoginsStorage())
+    val asyncStorage = Mockito.spy(AsyncLoginsStorageAdapter(storage))
 
     override val encryptionKey = "testing-key"
     override var syncConfig: SyncUnlockInfo? =
         SyncUnlockInfo("mock-kid", "mock-at", "mock-synckey", "https://mock.example.com/oauth/token")
 
-    override fun createLoginsStorage(): AsyncLoginsStorage = AsyncLoginsStorageAdapter(storage)
+    override fun createLoginsStorage(): AsyncLoginsStorage = asyncStorage
```
Comment (sashei) [inline app/src/test/java/mozilla/lockbox/mocks/MockLoginsStorage.kt]: 😍
