### PR TITLE
Handle Canceling Auth during Autofill

### LINKED ISSUE #449: In Autofill, tapping "Cancel" from Unlock does not return to fillable app
While filling, if a user cancels unlock, the user is left at a Lockbox splash screen instead of being returned to the fillable app.

## Prerequisites

* Lockbox is locked
* Fillable app is focused

## Steps to Reproduce

1. User taps "Unlock Firefox Lockbox"
   - presented with Unlock screen
2. User taps cancel

## Expected Results
User is returned to fillable app

## Actual Results
User sees Lockbox splash screen

## Workarounds
The user can tap the "Back" button at least once to return to the fillable app

### PR DESCRIPTION
**Pull request by linuxwolf**
Fixes #449

Ensure that if the user cancels authenticating during autofill, control returns back to the sending activity.

**NOTE**: this PR is not addressing any of the visual discrepancies in #421 or #436 
**NOTE**: The added tests are only covering the changes specific to this PR, even though the whole -Test class is new (to be addressed via #465)

_(**Required**: this reference (one or many) will be closed upon merge. Ideally it has the acceptance criteria and designs for features or fixes related to the work in this Pull Request.)_

## Testing and Review Notes

* Start with Lockbox app in the locked state, then open an app for autofill
* The user is returned to the originating app if dismissed:

    - tapping system "Back" button
    - tapping "Cancel" button if present
    - (for fingerprint unlock) tapping outside of the dialog

## Screenshots or Videos
Capture illustrates the following:
1. autofill prompt to unlock -> tap
2. overlay fingerprint unlock -> tap cancel
3. autofill prompt to unlock -> tap
4. overlay fingerprint unlock -> scan print
5. autofill search

autofilllock-print-2019-02-19

## To Do

- [x] add “WIP” to the PR title if pushing up but not complete nor ready for review
- [x] double check the original issue to confirm it is fully satisfied
- [x] add testing notes and screenshots in PR description to help guide reviewers
- [x] add unit tests
- [ ] request the "UX" team perform a design review (if/when applicable)
- [ ] make sure CI builds are passing (e.g.: fix lint and other errors)

### CODE REVIEW

File: app/src/main/java/mozilla/lockbox/presenter/AuthPresenter.kt [hunk 1]
```diff
@@ -39,7 +40,9 @@ class AuthPresenter(
 ) : Presenter() {
 
     override fun onViewReady() {
+        // taking values, or this ends up firing multiple times!
```
Comment (eliserichards) [inline app/src/main/java/mozilla/lockbox/presenter/AuthPresenter.kt]: Nit: remove comment

File: app/src/main/java/mozilla/lockbox/presenter/AuthPresenter.kt [hunk 2]
```diff
@@ -95,4 +103,18 @@ class AuthPresenter(
...
+        if (passwords != null) {
+            val response =
+                responseBuilder.buildFilteredFillResponse(view.context, passwords)
+                    ?: responseBuilder.buildFallbackFillResponse(view.context)
+            // This should send off to the searchable list
+            // https://github.com/mozilla-lockbox/lockbox-android/issues/421
+
+            view.setFillResponseAndFinish(response)
+        } else {
+            view.setFillResponseAndFinish(null)
```
Comment (eliserichards) [inline app/src/main/java/mozilla/lockbox/presenter/AuthPresenter.kt]: Why do we want the fill response to be null here and not `responseBuilder.buildFallbackFillResponse`?

File: app/src/main/java/mozilla/lockbox/presenter/AuthPresenter.kt [hunk 3]
```diff
@@ -52,33 +55,38 @@ class AuthPresenter(
...
             .addTo(compositeDisposable)
 
         view.unlockConfirmed
-            .filter { it }
             .subscribe {
-                unlock()
+                if (it) {
+                    unlock()
+                } else {
+                    finishResponse()
```
Comment (eliserichards) [inline app/src/main/java/mozilla/lockbox/presenter/AuthPresenter.kt]: Should this be followed by a Lock action?

File: app/src/main/java/mozilla/lockbox/presenter/AuthPresenter.kt (hunk 2 above)
Comment (linuxwolf) [reply app/src/main/java/mozilla/lockbox/presenter/AuthPresenter.kt]: fallback sets up a "Search ..." prompt while `null` sets up a "Unlock ..." prompt.

File: app/src/main/java/mozilla/lockbox/presenter/AuthPresenter.kt (hunk 1 above)
Comment (linuxwolf) [reply app/src/main/java/mozilla/lockbox/presenter/AuthPresenter.kt]: I can remove the comment, though I think it has value to indicate a dragon to future us.

File: app/src/main/java/mozilla/lockbox/presenter/AuthPresenter.kt (hunk 3 above)
Comment (linuxwolf) [reply app/src/main/java/mozilla/lockbox/presenter/AuthPresenter.kt]: at this stage, we know that `DataStore` is still definitely locked.  I'm hesitant to add a (re) lock given how async these flows end up being.

File: app/src/main/java/mozilla/lockbox/presenter/AuthPresenter.kt [hunk 4]
```diff
@@ -52,33 +55,38 @@ class AuthPresenter(
...
+                }
             }
             .addTo(compositeDisposable)
 
         dataStore.state
             .filter { it == DataStore.State.Unlocked }
-            .switchMap { responseBuilder.asyncFilter(pslSupport, dataStore.list) }
+            // switch to the latest non-empty list of ServerPasswords
+            // TODO: deal with the list really being empty ...
```
Comment (linuxwolf) [inline app/src/main/java/mozilla/lockbox/presenter/AuthPresenter.kt]: I filed #464 to address this.  It's only encountered if the user really truly has an empty list, but it can leave our Autofill service in limbo ...

File: app/src/main/java/mozilla/lockbox/presenter/AuthPresenter.kt (hunk 1 above)
Comment (eliserichards) [reply app/src/main/java/mozilla/lockbox/presenter/AuthPresenter.kt]: that's fine with me 😎

File: app/src/main/java/mozilla/lockbox/presenter/AuthPresenter.kt (hunk 4 above)
Comment (sashei) [reply app/src/main/java/mozilla/lockbox/presenter/AuthPresenter.kt]: good callout, let's make sure that gets uplifted in sprint planning tomorrow.

File: app/src/main/java/mozilla/lockbox/presenter/AuthPresenter.kt [hunk 5]
```diff
@@ -52,33 +55,38 @@ class AuthPresenter(
 
         lockedStore.onAuthentication
             .subscribe {
-                if (it is FingerprintAuthAction.OnAuthentication) {
-                    when (it.authCallback) {
-                        is FingerprintAuthCallback.OnAuth -> unlock()
-                        is FingerprintAuthCallback.OnError -> view.unlockFallback()
+                when (it) {
```
Comment (sashei) [inline app/src/main/java/mozilla/lockbox/presenter/AuthPresenter.kt]: I don't love nesting `when`s like this, it feels like a code smell to me. Ideally, we would refactor `FingerprintAuthAction` to have three cases `OnError`, `OnAuthentication`, `OnCancel` instead of needing to drill down into the `OnAuthentication` for the callback... Anyway, that's probably out of the scope of this PR unless you really feel like tackling it; otherwise I can file a follow-up issue.

File: app/src/main/java/mozilla/lockbox/presenter/AuthPresenter.kt [hunk 6]
```diff
@@ -52,33 +55,38 @@ class AuthPresenter(
...
 
         dataStore.state
             .filter { it == DataStore.State.Unlocked }
-            .switchMap { responseBuilder.asyncFilter(pslSupport, dataStore.list) }
+            // switch to the latest non-empty list of ServerPasswords
+            // TODO: deal with the list really being empty ...
+            .switchMap { dataStore.list }
+            .filter { it.isNotEmpty() }
+            .take(1)
+            .switchMap { responseBuilder.asyncFilter(pslSupport, Observable.just(it)) }
```
Comment (sashei) [inline app/src/main/java/mozilla/lockbox/presenter/AuthPresenter.kt]: using `Observable.just` also feels like a code smell to me; maybe there will be some refactoring when we come back around to address #465

File: app/src/main/java/mozilla/lockbox/presenter/AuthPresenter.kt (hunk 5 above)
Comment (linuxwolf) [reply app/src/main/java/mozilla/lockbox/presenter/AuthPresenter.kt]: I agree it should be changed and agree that it's out of scope for the issue/PR.  Added #466 to address.
