### PR TITLE
Suppress browser chooser after backing out of OpenWebsite action.

### LINKED ISSUE #460: Investigate previous screen/pop-up is displayed when returning to Lockbox from and resume(interrupt)
## Steps to reproduce
1. Install and launch Lockbox.
2. Tap on **"Get Started"** and the enter your email.
3. Login with valid credentials.
4. Tap on any entry 
5. From the entry screen tap on **`Web address`** while no browser is selected as default.
6. The **`Open with`** pop-up is displayed.
7. Tap on the `Back` button 3 times until the lockbox is minimized.
8. From the springboard tap on **`Lockbox`** and resume the app.

### Expected behavior
When returning to the `Lockbox` no additional pop-ups are displayed.
### Actual behavior
When returning to the `Lockbox` the **`Open with`** pop-up is displayed in the **"All entries"** screen

### Device information
* Firefox Lockbox version: 1.0 [build #2681](https://app.bitrise.io/build/bf9242396ba0f030)
* Samsung Galaxy Note 9(Android 8.1.0)
* Google Pixel 3 XL (Android P/9)

### Notes
No matter from what screen you tap the back button, when returning to the Lockbox the last option/pop-up is displayed.
[Video](https://drive.google.com/file/d/1o8sk5MdQX6zPvybbzXrIQQ_zAAsTOBSP/view?usp=sharing)
[logcat.txt](https://github.com/mozilla-lockbox/lockbox-android/files/2889660/logcat.txt)

### PR DESCRIPTION
**Pull request by jhugman**
Fixes #460

When the back button is pressed it has no effect on the `RouteStore.routes`; when the user relaunches the app, the route presenter resubscribes, and gets the replayed `OpenWebsite` route, so re-presents the Browser chooser dialog.

### CODE REVIEW

File: app/src/main/java/mozilla/lockbox/store/RouteStore.kt [hunk 1]
```diff
@@ -40,6 +40,14 @@ open class RouteStore(
     init {
         dispatcher.register
             .filterByType(RouteAction::class.java)
+            .flatMap {
+                when (it) {
+                    is RouteAction.OpenWebsite,
```
Comment (sashei) [inline app/src/main/java/mozilla/lockbox/store/RouteStore.kt]: want some tests :)
